"""Regenerate the eight self-contained TeX sources and their SVG diagrams.
Run: python3 drafts/catalog-063/generalized-mukai/diagrams/render.py
Requires XeLaTeX, xeCJK with Harano Aji, TikZ, and dvisvgm.
No booklet PDF is produced. Style follows the repository's MIT-licensed diagrams.
"""
from pathlib import Path
import subprocess, tempfile, re, html
root=Path(__file__).resolve().parent
preamble=(root/'preamble.tex').read_text()
with tempfile.TemporaryDirectory(prefix='math-digest-063-') as tmp:
    for body in sorted(root.glob('*.tikz')):
        for lang in ('ja','en'):
            name=body.stem+'.'+lang
            tex=root/(name+'.tex')
            tex.write_text('% Generated by render.py; edit preamble.tex and '+body.name+'\n'+preamble+'\n'+('\\Japanesetrue' if lang=='ja' else '\\Japanesefalse')+'\n\\begin{document}\n\\begin{tikzpicture}\n'+body.read_text()+'\n\\end{tikzpicture}\n\\end{document}\n')
            p=subprocess.run(['xelatex','-no-pdf','-no-shell-escape','-interaction=nonstopmode','-halt-on-error','-output-directory='+tmp,tex.name],cwd=root,capture_output=True,text=True)
            if p.returncode or re.search(r'Overfull \\[hv]box|Missing character:',p.stdout):
                raise RuntimeError(name+'\n'+p.stdout[-7000:])
            svgfile=root/(name+'.svg')
            subprocess.run(['dvisvgm','--no-fonts','--exact','--output='+str(svgfile),str(Path(tmp)/(name+'.xdv'))],check=True,capture_output=True)
            svg=svgfile.read_text()
            # Normalize quotes so the shared Markdown renderer prefixes every glyph ID.
            svg=re.sub(r"(\s[\w:-]+)='([^']*)'",lambda m:m[1]+'="'+html.escape(html.unescape(m[2]),quote=True)+'"',svg)
            prefix='generalized-mukai-'+name+'-'
            svg=re.sub(r'\bid="([^"]+)"',lambda m:'id="'+prefix+m[1]+'"',svg)
            svg=re.sub(r'(xlink:href|href)="#([^"]+)"',lambda m:m[1]+'="#'+prefix+m[2]+'"',svg)
            svg=svg.replace('<svg ', '<svg role="group" aria-label="'+name+' proof diagram" ',1)
            svgfile.write_text(svg)
            print(name,'OK',flush=True)
