import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {unified} from 'unified';
import remarkParse from 'remark-parse';
import remarkGfm from 'remark-gfm';
import remarkRehype from 'remark-rehype';
import rehypeStringify from 'rehype-stringify';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const papers=[['uniform-pluricanonical-iitaka','10 · Uniform Iitaka'],['lifting-adjoint-sections','07 · Supported lifting'],['effective-log-iitaka-fourfolds','13 · Fourfold Iitaka'],['abundance-after-nonvanishing','14 · Kähler after nonvanishing']];
const esc=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const css=`:root{--ink:#25322f;--link:#246657;--paper:#faf9f5;--line:#c6d2cc;--muted:#52615b}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:17px/1.95 Georgia,"Times New Roman","Yu Mincho","Hiragino Mincho ProN",serif}header{position:sticky;top:0;z-index:9;background:rgba(250,249,245,.98);border-bottom:1px solid var(--line);padding:12px max(18px,calc((100% - 1020px)/2));display:flex;align-items:center;justify-content:space-between;gap:16px;font:15px/1.5 -apple-system,BlinkMacSystemFont,"Hiragino Sans",sans-serif}.brand{font-weight:650}.langs{display:flex;gap:14px;white-space:nowrap}a{color:var(--link);text-underline-offset:3px}main{max-width:1020px;margin:auto;padding:24px 24px 70px}.notice{font:13px/1.6 -apple-system,BlinkMacSystemFont,"Hiragino Sans",sans-serif;color:var(--muted);margin-bottom:12px}nav{display:grid;grid-template-columns:repeat(2,1fr);gap:8px 20px;padding:15px 0 22px;border-bottom:1px solid var(--line);font:14px/1.7 -apple-system,BlinkMacSystemFont,"Hiragino Sans",sans-serif}nav a{padding:8px 10px;background:white;text-decoration:none;border:1px solid var(--line)}nav a[aria-current=page]{border-color:var(--link);background:#eef4f0;font-weight:700}article{margin:auto;max-width:900px}h1{font-size:clamp(26px,4vw,39px);line-height:1.45;font-weight:500;margin:35px 0 22px}h2{font-size:25px;font-weight:500;border-top:1px solid var(--line);padding-top:22px;margin-top:40px;line-height:1.55}h3{font-size:20px;line-height:1.6}p{margin:1em 0}blockquote{margin:24px 0;padding:1px 20px;border-left:3px solid var(--line);font:14px/1.8 -apple-system,BlinkMacSystemFont,"Hiragino Sans",sans-serif;color:var(--muted)}figure{margin:25px 0;overflow-x:auto}figure svg{display:block;width:100%;height:auto;background:white}table{width:100%;border-collapse:collapse;font-size:14px;line-height:1.8}th,td{padding:12px;border:1px solid var(--line);text-align:left;vertical-align:top}code{font-size:.85em;overflow-wrap:anywhere}mjx-container{max-width:100%;overflow-x:auto;overflow-y:hidden}.math-display{text-align:center;margin:24px 0;overflow:auto}footer{margin-top:45px;border-top:1px solid var(--line);padding-top:15px;font:12px/1.7 sans-serif;color:var(--muted)}@media(max-width:620px){body{font-size:16px}main{padding:16px 16px 45px}header{font-size:13px}nav{grid-template-columns:1fr;gap:5px}h2{font-size:22px}figure{margin-left:-8px;margin-right:-8px}table{display:block;overflow:auto}}`;
for(const [id,label] of papers)for(const lang of ['ja','en']){
 const directory=path.join(root,id);let md=await fs.readFile(path.join(directory,`article.${lang}.md`),'utf8');
 const maths=[];md=md.replace(/\$\$([\s\S]*?)\$\$|\$([^\n$]+)\$/g,(_,display,inline)=>{const index=maths.length;maths.push(display!==undefined?`<div class="math-display">\\[${esc(display.trim())}\\]</div>`:`<span class="math-inline">\\(${esc(inline)}\\)</span>`);return `MATHPLACEHOLDER${index}END`;});
 let html=String(await unified().use(remarkParse).use(remarkGfm).use(remarkRehype).use(rehypeStringify).process(md));
 html=html.replace(/<p>(MATHPLACEHOLDER\d+END)<\/p>/g,(_,token)=>token).replace(/MATHPLACEHOLDER(\d+)END/g,(_,i)=>maths[+i]);
 const imgs=[...html.matchAll(/<img src="(diagrams\/[^"<>]+\.svg)" alt="([^"]*)">/g)];
 for(const m of imgs){const svg=(await fs.readFile(path.join(directory,m[1]),'utf8')).replace(/<\?xml[^?]*\?>\s*/,'');html=html.replace(`<p>${m[0]}</p>`,`<figure role="img" aria-label="${m[2]}">${svg}</figure>`);}
 const nav=papers.map(([pid,title])=>`<a href="../${pid}/preview.${lang}.html"${pid===id?' aria-current="page"':''}>${title}</a>`).join('');
 const page=`<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${label} — OpenAI Math Digest</title><style>${css}</style><script>window.MathJax={tex:{inlineMath:[['\\\\(','\\\\)']],displayMath:[['\\\\[','\\\\]']],processEscapes:true},svg:{fontCache:'global'},options:{skipHtmlTags:['script','noscript','style','textarea','pre','code','svg']}};</script><script defer src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"></script></head><body><header><span class="brand">OpenAI Math Digest</span><div class="langs"><a href="preview.ja.html" lang="ja">日本語</a><a href="preview.en.html" lang="en">English</a></div></header><main><div class="notice">${lang==='ja'?'窓口A · カタログ034 · 未公開初稿の閲覧版':'Desk A · Catalog 034 · Unpublished draft preview'}</div><nav aria-label="${lang==='ja'?'担当4本の記事':'Four assigned articles'}">${nav}</nav><article>${html}</article><footer>${lang==='ja'?'作成済み原稿の閲覧用です。公開サイトへの組込みは本部が担当します。':'Preview of the saved manuscript. Site integration is handled by the central editor.'}</footer></main></body></html>`;
 await fs.writeFile(path.join(directory,`preview.${lang}.html`),page);console.log(`${id}/${lang}: ${imgs.length} diagrams; ${maths.length} formulas`);
}
