import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {unified} from 'unified';
import remarkParse from 'remark-parse';
import remarkGfm from 'remark-gfm';
import remarkRehype from 'remark-rehype';
import rehypeStringify from 'rehype-stringify';
const base=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const names=['arithmetic-stein-degree','relative-denominators','uniform-log-iitaka','kahler-log-abundance'];
const labels={ja:['算術的Stein次数','相対分母と有効線形系','一様な対数飯高写像','条件付きKähler豊富性'],en:['Arithmetic Stein degrees','Relative denominators','Uniform log Iitaka fibrations','Conditional Kähler abundance']};
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const css=`:root{--ink:#18232d;--link:#17617d;--paper:#f4f1ea;--line:#d5cdbf}*{box-sizing:border-box}html{scroll-padding-top:140px}body{margin:0;color:var(--ink);background:var(--paper);font:17px/1.95 Georgia,'Yu Mincho','Hiragino Mincho ProN',serif}header{position:sticky;top:0;z-index:10;background:rgba(244,241,234,.98);border-bottom:1px solid var(--line);padding:12px max(20px,calc((100vw - 1040px)/2));font:14px/1.6 -apple-system,BlinkMacSystemFont,'Hiragino Sans',sans-serif}.head{display:flex;justify-content:space-between;align-items:center;gap:15px}.brand{font-family:Georgia,serif;font-size:20px}.langs{display:flex;gap:12px;white-space:nowrap}nav{display:flex;gap:8px 20px;flex-wrap:wrap;margin-top:12px}nav a[aria-current=page]{font-weight:700;border-bottom:2px solid var(--link)}a{color:var(--link);text-underline-offset:3px}main{max-width:1040px;margin:40px auto;padding:0 22px 70px}article>p,article>h1,article>h2,article>h3,article>blockquote,article>ul{max-width:860px;margin-left:auto;margin-right:auto}h1{font-weight:500;font-size:clamp(27px,4vw,42px);line-height:1.5;margin-bottom:30px}h2{font-size:26px;font-weight:500;margin-top:65px;padding-bottom:12px;border-bottom:1px solid var(--line);line-height:1.6}h3{font-size:21px;line-height:1.6}p{margin-top:20px;margin-bottom:20px}blockquote{border-left:3px solid var(--link);padding:2px 20px;background:#ebe7df;font-size:14px;line-height:1.8}blockquote p{margin:8px 0}.proof{margin:32px 0;background:white;border:1px solid var(--line);padding:14px;overflow:auto}.proof svg{display:block;width:100%;height:auto;min-width:640px}table{border-collapse:collapse;width:100%;font-size:15px;line-height:1.8}th,td{border:1px solid var(--line);padding:12px;vertical-align:top;text-align:left}th{background:#ebe7df}.table-scroll{overflow:auto}mjx-container[display=true]{overflow-x:auto;overflow-y:hidden;padding:6px 0}code{font-size:.85em;overflow-wrap:anywhere}footer{margin-top:55px;padding-top:20px;border-top:1px solid var(--line);font:13px/1.8 sans-serif}.preview-note{font:13px/1.7 sans-serif;color:#52606b;margin-bottom:25px}@media(max-width:650px){body{font-size:16px}header{padding:10px 16px}nav{font-size:12px;gap:8px 14px}main{margin-top:26px;padding:0 16px 50px}h2{font-size:23px}table{min-width:750px}.proof{padding:8px}.brand{font-size:18px}}`;
for(const name of names)for(const lang of ['ja','en']){
 const dir=path.join(base,name);let md=fs.readFileSync(path.join(dir,`article.${lang}.md`),'utf8').replace(/^---\n[\s\S]*?\n---\n/,'');
 const equations=[];
 md=md.replace(/\$\$([\s\S]*?)\$\$|\$([^$\n]+)\$/g,(_,display,inline)=>{const idx=equations.length;equations.push({text:display??inline,display:display!==undefined});return `MATHPLACEHOLDER${idx}END`;});
 let html=String(await unified().use(remarkParse).use(remarkGfm).use(remarkRehype).use(rehypeStringify).process(md));
 html=html.replace(/MATHPLACEHOLDER(\d+)END/g,(_,i)=>{const m=equations[+i];return m.display?'\\['+esc(m.text)+'\\]':'\\('+esc(m.text)+'\\)';});
 html=html.replace(/<p><img src="(diagrams\/[^"<>]+\.svg)" alt="([^"]*)"><\/p>/g,(_,src,alt)=>{let svg=fs.readFileSync(path.join(dir,src),'utf8').replace(/<\?xml[^>]*\?>/,'');return `<figure class="proof" aria-label="${alt}">${svg}</figure>`;});
 html=html.replace(/<table>[\s\S]*?<\/table>/g,t=>`<div class="table-scroll">${t}</div>`);
 const nav=names.map((n,i)=>`<a ${n===name?'aria-current="page" ':''}href="../${n}/preview.${lang}.html">${i+1}. ${labels[lang][i]}</a>`).join('');
 const title=labels[lang][names.indexOf(name)];
 const doc=`<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} · OpenAI Math Digest</title><style>${css}</style><script>window.MathJax={tex:{inlineMath:[['\\\\(','\\\\)']],displayMath:[['\\\\[','\\\\]']]},svg:{fontCache:'global'}};</script><script defer src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"></script></head><body><header><div class="head"><span class="brand">OpenAI Math Digest</span><div class="langs"><a href="preview.ja.html" lang="ja">日本語</a><a href="preview.en.html" lang="en">English</a></div></div><nav>${nav}</nav></header><main><p class="preview-note">${lang==='ja'?'窓口Bの記事プレビュー — 公開前の概説草稿':'Worker B article preview — unpublished expository draft'}</p><article>${html}</article><footer><a href="article.${lang}.md">${lang==='ja'?'記事原稿':'Markdown source'}</a> · <a href="status.md">${lang==='ja'?'確認範囲と申し送り':'Verification scope and handoff'}</a><p>Design adapted from <a href="https://masataka123.github.io/geometry-paper-digest/">Geometry Paper Digest</a> (MIT).</p></footer></main></body></html>`;
 fs.writeFileSync(path.join(dir,`preview.${lang}.html`),doc);
 console.log(name,lang,equations.length,'math expressions,', (html.match(/class="proof"/g)||[]).length,'diagrams');
}
